Repository LesFruitsDefendus/saskatoon-ng, pull requests merged in 2022-06, with the labels that each got.

#301 Fix 300 PickLeaderAutocomplete now returns AuthUser, not Person
  saskatoon/member/autocomplete.py
Labels: high priority

#239 Add Harvest column in property detail view
  saskatoon/harvest/serializers.py
  saskatoon/sitebase/templates/app/detail_views/property/harvest_row.html
  saskatoon/sitebase/templates/app/detail_views/property/harvest_table.html
Labels: high priority

#312 Fix 311 - PersonUpdateForm email validation and auth_user creation
  saskatoon/member/forms.py
  saskatoon/member/validators.py
Labels: high priority

#313 Grab emails from property owner's comments (Person)
  saskatoon/harvest/admin.py
  saskatoon/member/models.py
Labels: high priority

#306 Refactor Harvest Serializer
  saskatoon/harvest/api.py
  saskatoon/harvest/serializers.py
  saskatoon/sitebase/templates/app/detail_views/harvest/about.html
  saskatoon/sitebase/templates/app/detail_views/harvest/breadcomb.html
  saskatoon/sitebase/templates/app/detail_views/harvest/comments.html
  saskatoon/sitebase/templates/app/detail_views/harvest/data_row.html
  saskatoon/sitebase/templates/app/detail_views/harvest/data_table.html
  saskatoon/sitebase/templates/app/detail_views/harvest/distribution/create_yield.html
  saskatoon/sitebase/templates/app/detail_views/harvest/distribution/recipient_select.html
  saskatoon/sitebase/templates/app/detail_views/harvest/distribution/tree_select.html
  saskatoon/sitebase/templates/app/detail_views/harvest/distribution/view.html
  saskatoon/sitebase/templates/app/detail_views/harvest/status.html
Labels: refactoring

#316 Fix 315 Make publish_date optional and simplify is_publishable
  saskatoon/harvest/forms.py
  saskatoon/harvest/models.py
  saskatoon/member/admin.py
  saskatoon/sitebase/templates/app/base/scripts.html
Labels: high priority

#320 Hotfix - add default filters to menu links to try and reduce loading time
  saskatoon/sitebase/templates/app/base/menu.html
Labels: high priority

#325 Hot fix serve pdf files
  saskatoon/saskatoon/settings.py
  saskatoon/sitebase/templates/app/index/pickleader.html
  saskatoon/sitebase/urls.py
  saskatoon/sitebase/views.py
Labels: high priority

#327 Refactor harvest list view
  saskatoon/harvest/api.py
  saskatoon/harvest/models.py
  saskatoon/harvest/serializers.py
  saskatoon/sitebase/templates/app/list_views/harvest/data_row.html
Labels: enhancement, refactoring, REST

#329 Speed Up Property List View
  saskatoon/harvest/api.py
  saskatoon/harvest/serializers.py
  saskatoon/sitebase/templates/app/list_views/property/data_row.html
Labels: enhancement, REST
